blog_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
#from . import views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register',user_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profile,name='user-profile'),
    path('ajax/validate_username/',user_views.validate_username, name='validate_username'),
    path('',include(('blogs.urls','blogs'),namespace='blogs')),
    path('verify-email/',user_views.send_verification_mail,name='verify-mail'),
    path('user-account/',user_views.user_account,name='user-account'),
    path('password-reset/',user_views.send_password_reset_mail,name='password-reset'),
    path('verify-otp/',user_views.verify_otp,name='verify-otp'),
    path('chat/',include(('chat.urls','chat'),namespace='chat')),
    path('order/',include(('order.urls','order'),namespace='order')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ,name='password_reset_done'
# ,name='password_reset_confirm'
#,name='password_reset_complete'

blogs/urls.py
from django.urls import path
from . import views
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    MyDraftListView,
    MyPostListView,
    UserPostListView,
    CommentUpdateView,
    CommentDeleteView,
    Search,
    FeedbackCreateView,
    Topic
    )
from users import views as user_views

urlpatterns = [
    path('', PostListView.as_view(), name='blogs-index'),
    path('s/',Search.as_view(),name='search'),
    path('topic/<topic>',Topic.as_view(),name='topic'),
    path('post/<int:pk>/',PostDetailView.as_view(),name='post-details'),
    path('post/new/',PostCreateView.as_view(),name='post-create'),
    path('post/<int:pk>/confirm_publish/',views.confirm_publish,name='post-publish'),
    path('post/<int:pk>/update/',PostUpdateView.as_view(),name='post-update'),
    path('post/<int:pk>/delete/',PostDeleteView.as_view(),name='post-delete'),
    path('post/<int:pk>/',PostDetailView.as_view(),name='post-details'),
    path('<username>/draft_list/',MyDraftListView.as_view(),name='draft-list'),
    path('<username>/post_list/',MyPostListView.as_view(),name='post-list'),
    path('<username>/profile/',user_views.user_profile,name='user-profile'),
    path('<username>/posts/',UserPostListView.as_view(),name='user-post-list'),
    path('post/<int:pk>/add_comment',views.AddComment,name='add-comment'),
    path('post/<int:pk>/update_comment',CommentUpdateView.as_view(),name='update-comment'),
    path('post/<int:pk>/delete_comment/',CommentDeleteView.as_view(),name='comment-delete'),
    path('<int:pk>/preference/<int:user_preference>/', views.post_preference, name='post-preference'),
    path('post/<int:blog_id>/<int:comment_id>/preference/<int:user_preference>/', views.comment_preference, name='comment-preference'),
    path('post/<int:blog_id>/feedback',FeedbackCreateView.as_view(),name='post-feedback')
]

chat/urls.py
from django.urls import path
from . views import SendMessageView

urlpatterns = [
    path('<receiver>/', SendMessageView.as_view(), name='send-msg'),
    ]

order/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.create_order, name='order'),
    path('checkout/', views.checkout, name='checkout'),
]

blogs/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse



# Create your models here.
class Post(models.Model):
    author  = models.ForeignKey('auth.User',on_delete = models.CASCADE)
    title = models.CharField(null=False, blank=False, max_length = 50)
    text = models.TextField(null=False, blank = False)
    created_date = models.DateTimeField(default = timezone.now)
    published_date = models.DateTimeField(blank = True, null = True)
    edited = models.BooleanField(default=False)
    likes = models.IntegerField(default = 0)
    dislikes = models.IntegerField(default = 0)
    thumbnail = models.ImageField(null=True, blank=True, upload_to='thumbnail_pics')
    TOPIC_CHOICE = (
        ('World','World'),
        ('Technology','Technology'),
        ('Design','Design'),
        ('Culture','Culture'),
        ('Business','Business'),
        ('Politics','Politics'),
        ('Opinion','Opinion'),
        ('Science','Science'),
        ('Health','Health'),
        ('Style','Style'),
        ('Travel','Travel'),
        ('Others','Others'),
    )
    topic = models.CharField(max_length = 11,choices = TOPIC_CHOICE, default="Others", blank=False, null=False)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        if self.published_date == None:
            return reverse('blogs:draft-list', kwargs={'username':str(self.author)})
        else:
            return reverse('blogs:blogs-index')

    def __str__(self):
        return self.title

class Comment(models.Model):
    author = models.ForeignKey('auth.User', on_delete = models.CASCADE)
    post = models.ForeignKey('blogs.Post', related_name='comments', on_delete = models.CASCADE)
    comment = models.TextField(null = False, blank = False)
    created_date = models.DateTimeField(default = timezone.now)
    likes = models.IntegerField(default = 0)
    dislikes = models.IntegerField(default = 0)

    def get_absolute_url(self):
        return reverse('blogs:post-details', kwargs={'pk':self.post.pk})

    def __str__(self):
        return self.comment

class PostPreference(models.Model):
    user = models.ForeignKey('auth.User',on_delete = models.CASCADE)
    post = models.ForeignKey(Post,on_delete = models.CASCADE)
    value = models.IntegerField()
    date = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.post.title


class CommentPreference(models.Model):
    user = models.ForeignKey('auth.User',on_delete = models.CASCADE)
    comment = models.ForeignKey(Comment,on_delete = models.CASCADE)
    value = models.IntegerField()
    date = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.comment

class PostReport(models.Model):
    user = models.ForeignKey('auth.User', on_delete = models.CASCADE)
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    FEEDBACK_CHOICE = (
        ('Nudity','Nudity'),
        ('Violence','Violence'),
        ('Harassment','Harassment'),
        ('Sucide or Self-Injury','Sucide or Self-Injury'),
        ('False News','False News'),
        ('Spam','Spam'),
        ('Unauthorized Sales','Unauthorized Sales'),
        ('Hate Speech','Hate Speech'),
        ('Terrosim','Terrosim'),
    )
    feedback = models.CharField(max_length = 30,choices = FEEDBACK_CHOICE,blank=False,null=False)
    feedback_text = models.TextField(max_length = 60,blank=True,null=True)
    date = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.feedback

    def get_absolute_url(self):
        return reverse('blogs:post-details', kwargs={'pk':self.post.pk})

blogs/views.py
from django.shortcuts import render, get_object_or_404, redirect
from . models import (
    Post,
    Comment,
    PostPreference,
    CommentPreference,
    PostReport )
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.utils import timezone
from django.urls import reverse,reverse_lazy
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.postgres.search import SearchVector
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
    )

def blank(text):
    count = 0
    for i in text:
        if i != ' ':
            count += 1
    if count <= 5:
        return 0
    else:
        return count

class PostListView(ListView):
    model = Post
    template_name = 'blogs/index.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=False).order_by('-published_date')


class PostDetailView(DetailView):
#    model = Post
    context_object_name = 'object'

    def get_queryset(self):
        return Post.objects.filter(pk=self.kwargs.get('pk'),published_date__lte=timezone.now())

    def get_context_data(self, **kwargs):
        context = super(PostDetailView,self).get_context_data(**kwargs)
        context['comments'] = Comment.objects.filter(post_id = self.kwargs.get('pk')).order_by('-created_date')
        if self.request.user.is_authenticated:
            context['post_pref'] = PostPreference.objects.filter(user = self.request.user,post_id = self.kwargs.get('pk')).first()
            context['com_pref'] = CommentPreference.objects.filter(user = self.request.user,comment_id = self.kwargs.get('comment_id')).first()

        page = self.request.GET.get('page', 1)
        paginator = Paginator(context['comments'],2)
        try:
            context['comments'] = paginator.page(page)
        except PageNotAnInteger:
            context['comments'] = paginator.page(1)
        except EmptyPage:
            context['comments'] = paginator.page(num_pages)

        return context

class Search(ListView):
    model = Post
    paginate_by = 5
    template_name = 'blogs/search.html'

    def get_context_data(self, **kwargs):
        context = super(Search,self).get_context_data(**kwargs)
        s = self.request.GET.get('search')
        if s:
            context['search'] = s
            context['results'] = Post.objects.filter(title__icontains=s)
            print(context['results'])
            return context

class Topic(ListView):
    model = Post
    paginate_by = 5
    template_name = 'blogs/topic.html'
    context_object_name = 'results'

    def get_queryset(self):
        return Post.objects.filter(topic=self.kwargs.get('topic'),published_date__lte=timezone.now()).order_by('-created_date')

    """def get_context_data(self, **kwargs):
        context = super(Search,self).get_context_data(**kwargs)
        s = get_object_or_404(Post, topic=self.kwargs.get('name'))
        if s:
#            context['search'] = s
            context['results'] = Post.objects.filter(topic__icontains=s)
#            print(context['results'])
            return context
    """


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title','topic','text','thumbnail']

    def form_valid(self, form):
        form.instance.author = self.request.user
        if self.request.POST.get('publish'):
            super().form_valid(form)
            post = form.instance
            post.save()
            return render(self.request,'blogs/confirm_publish.html',{'post':post})
        else:
            messages.success(self.request,f'Blog "{form.instance.title}" is Saved to Draft')
        return super().form_valid(form)

@login_required
def confirm_publish(request,pk):
    post = get_object_or_404(Post,pk=pk)
    if request.user == post.author:
        post.published_date = timezone.now()
        post.save()
        messages.success(request,f'Blog "{post.title}" is published')
        return redirect("blogs:blogs-index")
    else:
        raise PermissionDenied


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title','topic','text','thumbnail']

    def form_valid(self, form):
        form.instance.author = self.request.user
        post = self.get_object()
        if self.request.POST.get('publish'):
            super().form_valid(form)
            post = form.instance
            post.save()
            return render(self.request,'blogs/confirm_publish.html',{'post':post})
        else:
            if post.published_date != None:
#                print("post",post.edited)
                post.edited = True
                post.save()
            messages.success(self.request,f'Blog "{form.instance.title}" is Updated')
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDeleteView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    fields = ['comment']
    template_name = 'blogs/comment_update_form.html'


    def form_valid(self, form):
        form.instance.author = self.request.user
        comment = self.get_object()
        super().form_valid(form)
        comment = form.instance
        comment.save()
        messages.success(self.request,f'Comment "{form.instance.comment}" is Updated')
        return super().form_valid(form)

    def test_func(self):
        comment = self.get_object()
        if self.request.user == comment.author:
            return True
        return False

class CommentDeleteView(UserPassesTestMixin, LoginRequiredMixin, DeleteView):
    model = Comment
    def get_success_url(self):
        post = self.object.post
        return reverse_lazy('blogs:post-details',kwargs={'pk':post.pk},)

    def test_func(self):
        comment = self.get_object()
        if self.request.user == comment.author:
            return True
        return False


class MyDraftListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Post
    template_name = 'blogs/draft_list.html' #<app>/<model>_<viewtype>/html
    context_object_name = 'posts'

    def test_func(self):
        if self.request.user.username == self.kwargs.get('username'):
            return True
        return False

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user,published_date=None).order_by('-created_date')

class MyPostListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = Post
    template_name = 'blogs/post_list.html' #<app>/<model>_<viewtype>/html
    context_object_name = 'posts'

    def test_func(self):
        print("user:  ",self.request.user.username)
        print("useras:  ",self.kwargs.get('username'))
        if self.request.user.username == self.kwargs.get('username'):
            return True
        return False

    def get_queryset(self):
        return Post.objects.filter(author=self.request.user,published_date__isnull=False).order_by('-created_date')


class UserPostListView(ListView):
    model = Post
    template_name = 'blogs/user_post_list.html' #<app>/<model>_<viewtype>/html
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user,published_date__lte=timezone.now()).order_by('-created_date')

@login_required
def AddComment(request,pk):
    if request.method == "POST":
        c = request.POST.get('the_comment')
        print("value of comment= '",c,"'")
        if blank(c) == 0:
            return JsonResponse({})
        post = get_object_or_404(Post,pk = pk)
        comment = Comment()
        comment.post_id = pk
        comment.comment = c
        comment.author = request.user
        comment.created_date = timezone.now()
        comment.save()

        comments = Comment.objects.filter(post_id=pk).order_by('-created_date')
        context = {}
        context['result'] = 'Created succesfully'
        context['commenttpk'] = comment.pk
        context['comment'] = comment.comment
        context['created'] = comment.created_date

        return JsonResponse(context)
    else:
        return JsonResponse(context)


@login_required
def post_preference(request,pk,user_preference):
    if request.method == "GET":
        post = get_object_or_404(Post,pk = pk)
        obj = ''
        valueobj = ''
        context = {}
        try:
            obj = PostPreference.objects.get(user=request.user,post=post)
            valueobj = obj.value
            valueobj = int(valueobj)
            user_preference = int(user_preference)
            if valueobj != user_preference:
                obj.delete()

                upref = PostPreference()
                upref.user = request.user
                upref.post = post
                upref.value = user_preference

                if user_preference == 1 and valueobj != 1:
                    post.likes += 1
                    post.dislikes -= 1
                elif user_preference == 2 and valueobj != 2:
                    post.likes -= 1
                    post.dislikes += 1
                upref.save()
                post.save()
                if request.user.is_authenticated:

blogs/templates/blogs/comment_update_form.html
{% extends "blogs/base.html" %}
{% load static %}
{% block content %}
{% load crispy_forms_tags %}

<form class="" action="" method="post">
  {% csrf_token %}
  <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 font-italic">{{ comment.post.title }}</h1>
      <h3>Author : <a class="" href="{% url 'blogs:user-profile' object.author %}">
        {% if comment.post.author.profile.first_name == none %}
          {{comment.post.author }}
        {% endif %}
        {% if comment.post.author.profile.first_name %}
          {{ comment.post.author.profile.first_name }}
        {% endif %}
        {% if comment.post.author.profile.last_name %}
         {{ comment.post.author.profile.last_name }}
        {% endif %}
      </a></h3>
      <p class="lead my-3">{{ comment.post.text|truncatewords:30 }}</p>

  </div>
</div>
    {{form|crispy}}
    <button class="btn btn-success" type="submit" name="button">update</button>
    <a class="btn btn-danger" href="{% url 'blogs:comment-delete' comment.pk %}"  >Delete</a>
    <a class="btn btn-primary" href="{% url 'blogs:post-details' comment.post.pk %}"  >Cancel</a>

</form>

{% endblock content %}

blogs/templates/blogs/confirm_publish.html
{% extends 'blogs/base.html' %}
{% block content %}
<form class="" action="{% url 'blogs:post-publish' post.pk %}" method="POST">

  {% csrf_token %}
  <h6>Title: </h6><p>{{ post.title }}</p>
  <br>
  <h6>Topic: </h6><p>{{ post.topic }}</p>
  <br>
  <h6>Post: </h6><p>{{ post.text }}</p>
  <br>

  <h6>Thumbnail: </h6>
    {% if post.thumbnail %}
      <p>{{ post.thumbnail.url }}</p>
    {% else %}
      <p>No file selected</p>
    {% endif %}
  <br>
  <input id="inputEmail" name="confirm_publish" class="btn btn-primary" type="submit" value="Confirm Publish">
  <a class="btn btn-primary" href="{% url 'blogs:post-update' post.pk %}" role="button">Cancel</a>
</form>
{% endblock %}

blogs/templates/blogs/draft_list.html
{% extends 'blogs/base.html' %}
{% block content %}

<div class="card flex-md-row mb-4 shadow-sm ">
  <div class="card-body d-flex flex-column align-items-start">
    <h2 class="h1">Draft List</h2>
<ul>
  {% if posts %}
    {% for post in posts %}
      {% if post.author.pk == user.pk %}
        <li>
        <h5>  <a class="p-2 text-muted" href="{% url 'blogs:post-update' post.pk %}">{{ post.title }}</a></h5>
        </li>
      {% endif %}
    {% endfor %}
  {% else %}
    <h5>Draft list empty</h5>
  {% endif %}
  </div>
</div>

{% endblock %}

blogs/templates/blogs/post_detail.html
{% extends "blogs/base.html" %}
{% load static %}

{% block javascript %}

  <script type="text/javascript">
    function create_comment(){
      console.log("Create POst Working!!")
      console.log($("#comment").val())
      $.ajax({
        url: '{% url 'blogs:add-comment' object.pk %}',
        type: "POST",
        data: {
          'the_comment' : $("#comment").val(),
          'csrfmiddlewaretoken': '{{ csrf_token }}'
        },
        success: function(json){
          $("#comment").val('');
          console.log(json);
          $("#talk").load("blogs/comments.html");
          console.log("succes");
        },
        error: function(xhr,errmsg,err){
          $("#result").html("<div class='alert-box alert redius' data-alert>Opps! Something went wrong: "+errmsg+"<a href='#' class='close'>&times;</a></div>")
        }
      });
    };

    function post_like_func(){
      console.log("posd Like!! ")
      $.ajax({
        url: '{% url 'blogs:post-preference' object.pk 1 %}',
        type: "GET",
        data: {},
        success: function(context){
          console.log("posdefkj Like!!== ")
          if(context.value == 1)
          {
            $("#post_like").addClass('btn-group-sm btn-outline-success')
            $("#post_dislike").removeClass('btn-group-sm btn-outline-success')
            $("#post_dislike").addClass('btn-group-sm btn-outline-secondary')
            $("#post_like").text(context.json_post_like+'|Unlike')
            $("#post_dislike").text(context.json_post_dislike+'|Dislike')
          }
          else if(context.value == null)
          {
            $("#post_like").removeClass('btn-group-sm btn-outline-success')
            $("#post_like").addClass('btn-group-sm btn-outline-secondary')
            $("#post_like").text(context.json_post_like+'|Like')
            $("#post_dislike").text(context.json_post_dislike+'|Dislike')
          }


          console.log("succes");
        },
        error: function(){

        }
      });
    };

    function post_dislike_func(){
      console.log("posdefkj Like!! ")
      $.ajax({
        url: '{% url 'blogs:post-preference' object.pk 2 %}',
        type: "GET",
        data: {},
        success: function(context){
          if(context.value == 2)
          {
            $("#post_dislike").addClass('btn-group-sm btn-outline-success')
            $("#post_like").removeClass('btn-group-sm btn-outline-success')
            $("#post_like").addClass('btn-group-sm btn-outline-secondary')
            $("#post_like").text(context.json_post_like+'|Like')
            $("#post_dislike").text(context.json_post_dislike+'|Undislike')
          }
          else if(context.value == null)
          {
            $("#post_dislike").removeClass('btn-group-sm btn-outline-success')
            $("#post_dislike").addClass('btn-group-sm btn-outline-secondary')
            $("#post_like").text(context.json_post_like+'|Like')
            $("#post_dislike").text(context.json_post_dislike+'|Dislike')
          }

          console.log("succes");
        },
        error: function(){}
      });
    };

    function com_like_func(){
      console.log("posdefkj Like!! ")
      var a = $("#com_like").attr("data_catid");
      $.ajax({
        url: a,
        type: "GET",
        data: {},
        success: function(context){
          if(context.com_value == 1)
          {
            $("#com_like").addClass('btn-group-sm btn-outline-success')
            $("#com_dislike").removeClass('btn-group-sm btn-outline-success')
            $("#com_dislike").addClass('btn-group-sm btn-outline-secondary')
            $("#com_like").text(context.json_com_like+'|Unlike')
            $("#com_dislike").text(context.json_com_dislike+'|Dislike')
          }
          else if(context.com_value == null)
          {
            $("#com_like").removeClass('btn-group-sm btn-outline-success')
            $("#com_like").addClass('btn-group-sm btn-outline-secondary')
            $("#com_like").text(context.json_com_like+'|Like')
            $("#com_dislike").text(context.json_com_dislike+'|Dislike')
          }

          console.log("succesas  = ",context.com_value);
        },
      });
    };

    function com_dislike_func(){
      console.log("posdefkj Like!! ")
      var a = $("#com_dislike").attr("data_catid");
      $.ajax({
        url: a,
        type: "GET",
        data: {},
        success: function(context){
          if(context.com_value == 2)
          {
            $("#com_dislike").addClass('btn-group-sm btn-outline-success')
            $("#com_like").removeClass('btn-group-sm btn-outline-success')
            $("#com_like").addClass('btn-group-sm btn-outline-secondary')
            $("#com_like").text(context.json_com_like+'|Like')
            $("#com_dislike").text(context.json_com_dislike+'|Undislike')
          }
          else if(context.value == null)
          {
            $("#com_dislike").removeClass('btn-group-sm btn-outline-success')
            $("#com_dislike").addClass('btn-group-sm btn-outline-secondary')
            $("#com_like").text(context.json_com_like+'|Like')
            $("#com_dislike").text(context.json_com_dislike+'|Dislike')
          }
          console.log("succes=");
        },
      });
    };

  $("#comment_form").on('submit', function(event){
      event.preventDefault();
      console.log("form submitted!!");
      create_comment();
    })

    $("#post_like").on('click',function(event){

        event.preventDefault();
        console.log("Post like!!");
        post_like_func(post_like);

    })

      $("#post_dislike").on('click',function(event){
        event.preventDefault();
        console.log("Post like!!");
        post_dislike_func(post_dislike);
    })

    $("#com_like").on('click',function(event){
      event.preventDefault();
      console.log("Post like!!");
      com_like_func();
  })

    $("#com_dislike").on('click',function(event){
      event.preventDefault();
      console.log("Post like!!");
      com_dislike_func();
  })


  </script>

{% endblock javascript %}

{% block content %}

<div>
  <div class="jumbotron p-3 p-md-5 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 font-italic">{{ object.title }}</h1>
      <h3>Author : <a class="" href="{% url 'blogs:user-profile' object.author %}">
        {% if object.author.profile.first_name == none %}
          {{ object.author }}
        {% endif %}
        {% if object.author.profile.first_name %}
          {{ object.author.profile.first_name }}
        {% endif %}
        {% if object.author.profile.last_name %}
         {{ object.author.profile.last_name }}
        {% endif %}
      </a></h3>
      <p class="lead my-3">{{ object.text|linebreaks }}</p>

      <div id="post" class="btn-group mr-2">

        {% if user.is_authenticated %}

        {% if post_pref.value == 1 %}
          <a id="post_like" data-catid1="{{ user.is_authenticated }}" onclick="" data-catid2="1" href="" class="btn btn-sm btn-outline-success">
        {% else %}
          <a id="post_like" data-catid1="{{ user.is_authenticated }}" onclick="" data-catid2="1" href="" class="btn btn-sm btn-outline-secondary">
        {% endif %}

            {% if json_post_like %}
            {{ json_post_like }}
            {% else %}
            {{ object.likes }}|
            {% endif %}
            {% if post_pref.value == 1 %}
              Unike
            {% else %}
              Like
            {% endif %}

          </a>

          {% if post_pref.value == 2 %}
            <a id="post_dislike" data-catid1="{{ object.pk }}" onclick="" data-catid2="1" href="" class="btn btn-sm btn-outline-success">
          {% else %}
            <a id="post_dislike" data-catid1="{{ object.pk }}" onclick="" data-catid2="1" href="" class="btn btn-sm btn-outline-secondary">
          {% endif %}
            {{ object.dislikes }}|
            {% if post_pref.value == 2 %}
              Undislike
            {% else %}
              Dislike
            {% endif %}
            </a>

            {% else %}
          <div id="post" class="btn-group mr-2">
          <a  data-catid1="{{ object.pk }}" onclick="" data-catid2="1" href="{% url 'login' %}?next=/post/{{ object.pk }}" class="btn btn-sm btn-outline-secondary">{{object.likes}}|Like</a>
          <a  data-catid1="{{ object.pk }}" onclick="" data-catid2="1" href="{% url 'login' %}?next=/post/{{ object.pk }}" class="btn btn-sm btn-outline-secondary">{{object.dislikes}}|Dislike</a>
          </div>
          {% endif %}



        {% if user == object.author %}


          <a class="btn btn-sm btn-outline-secondary" href="{% url 'blogs:post-update' object.pk %}">Edit</a>

        {% endif %}
    </div>

    <a href="{% url 'blogs:post-feedback' object.pk %}">Report</a>

    {% if object.edited == true %}
      edited
    {% endif %}

  </div>
</div>

{% include "blogs/comments.html" %}

<div class="card flex-md-row mb-4 shadow-sm">
  <div class="card-body d-flex flex-column align-items-start">
    {% include "blogs/comment_form.html" %}
  </div>
</div>

{% endblock content %}

blogs/templates/blogs/post_form.html
{% extends "blogs/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="card flex-md-row mb-4 shadow-sm ">
  <div class="card-body d-flex flex-column align-items-start">
    <h1>Blog Post</h1>
      <form class="" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        {% if object.published_date == None %}
          <button class="btn btn-primary" type="submit" name="save_to_draft">Save to Draft</button>
          <input id="inputEmail" name="publish" class="btn btn-primary" type="submit" value="Publish">
        {% else %}
          <button class="btn btn-primary" type="submit" name="button">Save</button>
        {% endif %}

        {% if object.id == None %}
          <a class="btn btn-primary" href="{% url 'blogs:blogs-index' %}" role="button">Cancel</a>
        {% else %}
          <a class="btn btn-primary ml=5" href="{% url 'blogs:post-delete' object.id %}" role="button">Delete</a>
        {% endif %}

      </form>

    </div>
    </div>
{% endblock content %}