blog_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
#from . import views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register',user_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profile,name='user-profile'),
    path('ajax/validate_username/',user_views.validate_username, name='validate_username'),
    path('',include(('blogs.urls','blogs'),namespace='blogs')),
    path('verify-email/',user_views.send_verification_mail,name='verify-mail'),
    path('user-account/',user_views.user_account,name='user-account'),
    path('password-reset/',user_views.send_password_reset_mail,name='password-reset'),
    path('verify-otp/',user_views.verify_otp,name='verify-otp'),
    path('chat/',include(('chat.urls','chat'),namespace='chat')),
    path('order/',include(('order.urls','order'),namespace='order')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ,name='password_reset_done'
# ,name='password_reset_confirm'
#,name='password_reset_complete'

blogs/urls.py
from django.urls import path
from . import views
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    MyDraftListView,
    MyPostListView,
    UserPostListView,
    CommentUpdateView,
    CommentDeleteView,
    Search,
    FeedbackCreateView,
    Topic
    )
from users import views as user_views

urlpatterns = [
    path('', PostListView.as_view(), name='blogs-index'),
    path('s/',Search.as_view(),name='search'),
    path('topic/<topic>',Topic.as_view(),name='topic'),
    path('post/<int:pk>/',PostDetailView.as_view(),name='post-details'),
    path('post/new/',PostCreateView.as_view(),name='post-create'),
    path('post/<int:pk>/confirm_publish/',views.confirm_publish,name='post-publish'),
    path('post/<int:pk>/update/',PostUpdateView.as_view(),name='post-update'),
    path('post/<int:pk>/delete/',PostDeleteView.as_view(),name='post-delete'),
    path('post/<int:pk>/',PostDetailView.as_view(),name='post-details'),
    path('<username>/draft_list/',MyDraftListView.as_view(),name='draft-list'),
    path('<username>/post_list/',MyPostListView.as_view(),name='post-list'),
    path('<username>/profile/',user_views.user_profile,name='user-profile'),
    path('<username>/posts/',UserPostListView.as_view(),name='user-post-list'),
    path('post/<int:pk>/add_comment',views.AddComment,name='add-comment'),
    path('post/<int:pk>/update_comment',CommentUpdateView.as_view(),name='update-comment'),
    path('post/<int:pk>/delete_comment/',CommentDeleteView.as_view(),name='comment-delete'),
    path('<int:pk>/preference/<int:user_preference>/', views.post_preference, name='post-preference'),
    path('post/<int:blog_id>/<int:comment_id>/preference/<int:user_preference>/', views.comment_preference, name='comment-preference'),
    path('post/<int:blog_id>/feedback',FeedbackCreateView.as_view(),name='post-feedback')
]

chat/urls.py
from django.urls import path
from . views import SendMessageView

urlpatterns = [
    path('<receiver>/', SendMessageView.as_view(), name='send-msg'),
    ]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
#from phone_field import PhoneField

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    first_name = models.CharField(max_length=50,blank=True,null=True)
    last_name = models.CharField(max_length=50,blank=True,null=True)
    about = models.TextField(blank=True,null=True)
    email = models.EmailField(blank = True,null = True)
    school = models.CharField(max_length=70,blank=True,null=True)
    college = models.CharField(max_length=70,blank=True,null=True)
    work = models.CharField(max_length=70,blank=True,null=True)
    skills = models.CharField(max_length=70,blank=True,null=True)
    current_city = models.CharField(max_length=70,blank=True,null=True)
#    phon_no = PhoneField(max_length=12,blank=True,null=True)
    website = models.URLField(blank=True,null=True)
    birth_day = models.DateField(blank=True,null=True)
    otp = models.IntegerField(blank=True,null=True)
    GENDER_CHOICES = (
        ('Male','Male'),
        ('Female','Female'),
        ('Others','Others'),
    )
    gender = models.CharField(max_length=6,choices=GENDER_CHOICES,blank=True,null=True)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (60,60)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from . models import Profile

class UserCreationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget = forms.PasswordInput())
    email = forms.EmailField()

    class Meta():
        model = User
        fields = ('username','email','password','confirm_password')

    def clean(self):
        cleaned_data = super(UserCreationForm, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('confirm_password')
        if len(password) > 7:
            if password and confirm_password:
                if password != confirm_password:
                    raise forms.ValidationError(
                        "Password and Confirm Password didn't match"
                    )
        else:
            raise forms.ValidationError(
                "Password must have atleast 8 characters"
            )


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            'first_name',
            'last_name',
            'gender',
            'birth_day',
            'about',
            'school',
            'work',
            'skills',
            'current_city',
#            'phon_no',
            'website',
            'image'
            ]

class EmailVerificationForm(forms.Form):
    email = forms.EmailField(required = True)

class PasswordResetForm(forms.Form):
    username = forms.CharField(required = True)

class OtpVerificationForm(forms.Form):
    otp = forms.CharField(required = True)

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . forms import (
    UserCreationForm,
    UserUpdateForm,
    ProfileUpdateForm,
    EmailVerificationForm,
    PasswordResetForm,
    OtpVerificationForm)
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponse,  HttpResponseRedirect
from django.core.mail import send_mail
from django.conf import settings
from random import randint
from . models import Profile
from django.urls import reverse
# Create your views here.

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.set_password(user.password)
            user.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Account created for {username}!')
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request,'users/registration.html',{'form':form})

@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST,instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                    request.FILES,
                                    instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request,f'Your account has been updated!')
            return redirect('user-profile')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form':u_form,
        'p_form':p_form
    }
    return render(request,'users/profile.html',context)


def user_profile(request,username):
    user = get_object_or_404(User,username=(username))
    prof = user.profile
    return render(request,'users/user_profile1.html',{'prof':prof})

def validate_username(request):
    username = request.GET.get('username', None)
    data = {
        'is_taken': User.objects.filter(username=username).exists()
    }
    return JsonResponse(data)


def send_verification_mail(request):
    if request.method == 'POST':
        context = {}
        form = EmailVerificationForm(request.POST)
        context = {'form':form}
        if form.is_valid():
            receiver_mail = form.cleaned_data.get('email')

            print("mail == ",receiver_mail)
            send_mail(
                'hii',
                'this is message',
                settings.EMAIL_HOST_USER,
                [receiver_mail],
                fail_silently = False,
            )
            messages.success(request,f'A conformation mail has been sent to your registered email id')
    else:
        form = EmailVerificationForm(request.POST)
        context = {
            'form':form
        }
    return render(request,'users/email_verification_form.html',context)

def send_password_reset_mail(request):
    if request.method == 'POST':
        context = {}
        form = PasswordResetForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            if User.objects.filter(username__iexact=username).exists():
                obj = get_object_or_404(User,username__iexact=username)
                otp = randint(111111,999999)
                receiver_mail = obj.email
                obj.profile.otp = otp
                obj.save()
                print("Otp = ",obj.profile.otp)
                message = 'your one time password is '+str(otp)
                send_mail(
                    'hii',
                    message,
                    settings.EMAIL_HOST_USER,
                    [receiver_mail],
                    fail_silently = False,
                )
                form = OtpVerificationForm()
                context = {'form':form,'username':username}
                messages.success(request,f'A conformation mail has been sent to your registered email id')
                return render(request,'users/verify_otp.html',context);
            else:
                context = {'form':form}
                messages.success(request,f'Invalid username')
                return render(request,'users/password_reset_form.html',context)
    else:
        form = PasswordResetForm()
        context = {'form':form}
        return render(request,'users/password_reset_form.html',context)

def verify_otp(request):
    if request.method == 'POST':
        context = {}
        form = OtpVerificationForm(request.POST)
        if form.is_valid():
            otp = form.cleaned_data.get('otp')
            otp = int(otp)
            username = request.POST.get('username')
            print("Username = ",username)
            obj = get_object_or_404(User,username__iexact=username)
            p_otp = obj.profile.otp
            print("otp = ",otp,"p_otp = ",p_otp)
            if p_otp == otp:
                return HttpResponseRedirect(reverse('blogs:blogs-index'))
            else:
                form = OtpVerificationForm()
                context = {'form':form,'username':username}
                return render(request,'users/verify_otp.html',context);


def user_account(request):
    return render(request,'users/user_account.html',{})

users/templates/users/email_verification_form.html
{% extends "blogs/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="card flex-md-row mb-4 shadow-sm ">
  <div class="card-body d-flex flex-column align-items-start">
      <form class="" action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit" name="button">Verify</button>

      </form>

    </div>
    </div>
{% endblock content %}

users/templates/users/login.html
{% extends "blogs/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block head_content %}
  <link rel="stylesheet" href="{% static 'floating-labels.css' %}">
{% endblock %}

{% block content %}

<div class="card flex-md-row mb-4 shadow-sm ">
  <div class="card-body d-flex flex-column align-items-start">
      <form class="form-signin" action="" method="post">
        <div class="text-center mb-4">
          <h3 class="h2">Login</h3>
        </div>
        {% csrf_token %}
        {% if form.non_field_errors %}
          {% for error in form.non_field_errors %}
              <div class="alert alert-success">
                {{ error }}
              </div>
            {% endfor %}
        {% endif %}

        {% for field in form %}
          <div class="form-label-group">
            <input id="id_{{field.html_name}}" class="textinput textInput form-control {% if field.errors %}is-invalid{% endif %}" name="{{ field.html_name }}" placeholder="" required="true" autofocus="" type="{% if field.html_name == 'password' %}password{% endif %}">
            <label for="id_{{ field.html_name }}">{{ field.html_name|title }}</label>
            {% if field.errors %}
              <p id="error_{{forloop.counter}}_id_{{field.html_name}}" class="invalid-feedback"><strong>This field is required.</strong></p>
            {% endif %}
            {% if field.help_text %}
              <p class="help">{{ field.help_text|safe }}</p>
            {% endif %}
          </div>
          {% endfor %}

        <button class="btn btn-primary" type="submit" name="button">Login</button>
        <a href="{% url 'password-reset' %}">Forgot password?</a>
        <br>
        Or need an account? <a href="{% url 'register' %}">Register</a> here
      </form>

    </div>
    </div>

{% endblock content %}

users/templates/users/logout.html
{% extends "blogs/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="">
      <h2>Yoy have logged out!!</h2>
      <a href="{% url 'login' %}">Login Again</a>
      

    </div>
{% endblock content %}

users/templates/users/password_reset_form.html
{% extends "blogs/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="card flex-md-row mb-4 shadow-sm ">
  <div class="card-body d-flex flex-column align-items-start">
      <form class="" action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit" name="button">Verify</button>

      </form>

    </div>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "blogs/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.image.url }}" alt="">
        <div class="media-body">
          {% if user.profile.first_name == none %}
            <h2 class="account-heading">{{ user.username }}</h2>
          {% endif %}
          <h2 class="account-heading">
            {% if user.profile.first_name %}
              {{ user.profile.first_name }}
            {% endif %}
            {% if user.profile.last_name %}
              {{ user.profile.last_name }}
            {% endif %}
            </h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
      <form class="" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="from-group">
          <legend class="border-bottom mb-4">Profile Info of: {{ user.username }}</legend>
            {{ u_form|crispy }}
            {{ p_form|crispy }}
        </fieldset>
        <button class="btn btn-primary" type="submit" name="button">Update</button>
      </form>
      </div>

{% endblock content %}

users/templates/users/registration.html
{% extends "blogs/base.html" %}
{% load crispy_forms_tags %}

{% block javascript %}

  <script type="text/javascript">
      $("#id_username").change(function(){
      var username = $(this).val();
      console.log(username);

      $.ajax({
        url: '{% url 'validate_username' %}',
        data: {
          'username': username
        },
        dataType: 'json',
        success: function(data){
          if(data.is_taken){
            alert('A user with this username already exists');
          }
        }
      })
    });


  </script>

{% endblock javascript %}

{% block content %}
    <div class="">
      <form class="" action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit" name="button">Register</button>
      </form>

    </div>
{% endblock content %}

users/templates/users/user_account.html
{% extends "blogs/base.html" %}
{% block content %}
<div class="container">
	<div class="row">
		<div class="col-lg-3 col-sm-6">

            <div class="card hovercard">
                <div class="cardheader">

                </div>
                <div class="avatar">
                    <img alt="" src="http://lorempixel.com/100/100/people/9/">
                </div>
                <div class="info">
                    <div class="title">
                        <a target="_blank" href="https://scripteden.com/">Script Eden</a>
                    </div>
                    <div class="desc">Passionate designer</div>
                    <div class="desc">Curious developer</div>
                    <div class="desc">Tech geek</div>
                </div>
                <div class="bottom">
                    <a class="btn btn-primary btn-twitter btn-sm" href="https://twitter.com/webmaniac">
                        <i class="fa fa-twitter"></i>
                    </a>
                    <a class="btn btn-danger btn-sm" rel="publisher"
                       href="https://plus.google.com/+ahmshahnuralam">
                        <i class="fa fa-google-plus"></i>
                    </a>
                    <a class="btn btn-primary btn-sm" rel="publisher"
                       href="https://plus.google.com/shahnuralam">
                        <i class="fa fa-facebook"></i>
                    </a>
                    <a class="btn btn-warning btn-sm" rel="publisher" href="https://plus.google.com/shahnuralam">
                        <i class="fa fa-behance"></i>
                    </a>
                </div>
            </div>

        </div>

	</div>
</div>
{% endblock content %}

users/templates/users/user_profile.html
{% extends "blogs/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<br><br><br>
<div class="card flex-md-row mb-4 shadow-sm ">
  <div class="card-body d-flex flex-column align-items-start">

    <div class="container">
      <img height="125" width="125" class="rounded-circle account-img" src="{{ prof.image.url }}" alt="">
      <div class="media">

        <div class="media-body">

          <p class="mb-1 text-muted h4">
          Name:
          {% if prof.first_name == none %}
            {{ prof.user }}
          {% endif %}
          {% if prof.first_name %}
            {{ prof.first_name }}
          {% endif %}
          {% if prof.last_name %}
            {{ prof.last_name }}
          {% endif %}
          </p>

      <p class="mb-1 text-muted h4">
        Gender:
        {% if prof.gender == none %}
          Not set
        {% else %}
          {{ prof.gender }}
        {% endif %}
      </p>

      <p class="mb-1 text-muted h4">
        School:
        {% if prof.school == none %}
          Not set
        {% else %}
          {{ prof.school }}
        {% endif %}
      </p>

      <p class="mb-1 text-muted h4">
        College:
        {% if prof.college == none %}
          Not set
        {% else %}
          {{ prof.college }}
        {% endif %}
      </p>

      <p class="mb-1 text-muted h4">
        Current City:
        {% if prof.current_city == none %}
          Not set
        {% else %}
          {{ prof.current_city }}
        {% endif %}
      </p>

      <p class="mb-1 text-muted h4">
        Website:
        {% if prof.website == none %}
          Not set
        {% else %}
          {{ prof.website }}
        {% endif %}
      </p>

        </div>

      </div>
      <br>
      <div class="">
        <a href="{% url 'blogs:user-post-list' prof.user %}" class='btn btn-primary ml-4 h4'>Blogs</a>
      </div>
    </div>
  </div>
  </div>

{% endblock %}

users/templates/users/user_profile1.html
{% extends 'blogs/base.html' %}
{% load static %}
{% block content %}
<div class="">
	<div class="row">
		<div class="col-sm-2">

		</div>
		<div class="col-12 col-sm-6 col-lg-8">

            <div class="card hovercard">
                <div class="cardheader" style="background: url('{{ prof.image.url }}');background-size:cover;">

                </div>
                <div class="avatar">
                    <img alt="" src="{{ prof.image.url }}">
                </div>
                <div class="info">
                    <div class="title">
											<p class="mb-1 text-muted h2">
											{% if prof.first_name == none %}
												{{ prof.user }}
											{% endif %}
											{% if prof.first_name %}
												{{ prof.first_name }}
											{% endif %}
											{% if prof.last_name %}
												{{ prof.last_name }}
											{% endif %}
											</p>
                    </div>
                    <div class="desc">Passionate designer</div>
                    <div class="desc">Curious developer</div>
                    <div class="desc">Tech geek</div>
                </div>
                <div class="bottom">
                    <a class="btn btn-primary btn-twitter btn-sm" href="https://twitter.com/webmaniac">
                        <img height=30 width = 30 src="/media/twitter.png" alt="">
                    </a>
                    <a class="btn btn-danger btn-sm" rel="publisher" href="https://plus.google.com/+ahmshahnuralam">
                        <i class="fa fa-google-plus"></i>
                    </a>
                    <a class="btn btn-primary btn-sm" rel="publisher"
                       href="https://plus.google.com/shahnuralam">
                        <i class="fa fa-facebook"></i>
                    </a>
                    <a class="btn btn-warning btn-sm" rel="publisher" href="https://plus.google.com/shahnuralam">
                        <i class="fa fa-behance"></i>
                    </a>
                </div>
								<div class="">
									<a href="#" class="btn btn-primary">follow</a>
									<a href="#" class="btn btn-primary">following</a>

									{% if user != prof.user %}
									<a href="{% url 'chat:send-msg' prof.user %}" class="btn btn-primary">message</a>
									{% endif %}
								</div>
            </div>

        </div>

	</div>
</div>
{% endblock %}

users/templates/users/verify_otp.html
{% extends "blogs/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="card flex-md-row mb-4 shadow-sm ">
  <div class="card-body d-flex flex-column align-items-start">
      <form class="" action="{% url 'verify-otp' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="username" value="{{ username }}">
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit" name="button">Verify</button>

      </form>

    </div>
    </div>
{% endblock content %}