blog_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
#from . import views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register',user_views.register,name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profile,name='user-profile'),
    path('ajax/validate_username/',user_views.validate_username, name='validate_username'),
    path('',include(('blogs.urls','blogs'),namespace='blogs')),
    path('verify-email/',user_views.send_verification_mail,name='verify-mail'),
    path('user-account/',user_views.user_account,name='user-account'),
    path('password-reset/',user_views.send_password_reset_mail,name='password-reset'),
    path('verify-otp/',user_views.verify_otp,name='verify-otp'),
    path('chat/',include(('chat.urls','chat'),namespace='chat')),
    path('order/',include(('order.urls','order'),namespace='order')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# ,name='password_reset_done'
# ,name='password_reset_confirm'
#,name='password_reset_complete'

chat/urls.py
from django.urls import path
from . views import SendMessageView

urlpatterns = [
    path('<receiver>/', SendMessageView.as_view(), name='send-msg'),
    ]

order/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.create_order, name='order'),
    path('checkout/', views.checkout, name='checkout'),
]

order/models.py
from django.db import models

class Order(models.Model):
    order_id = models.CharField(max_length = 100, unique=True)
    price = models.DecimalField(max_digits=100, decimal_places=2)

    def __str__(self):
        return self.order_id

order/views.py
import razorpay
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseRedirect
client = razorpay.Client(auth=("rzp_test_Qrum48VNd3R8T4", "J3cS08M6EoJRBF1M1o5uVWGu"))

def create_order(request):
    order_amount = 5000
    order_currency = 'INR'
    order_receipt = 'order_rcptid_11'
    notes = {'Shipping address': 'Bommanahalli, Bangalore'}   # OPTIONAL
    resp = client.order.create(dict(amount=order_amount, currency=order_currency, receipt=order_receipt, notes=notes, payment_capture='0'))
    id = resp['id']
    return render(request, 'order/create.html', {'id': id})
    #return redirect('https://rzp.io/l/Fp59h7G')


@csrf_exempt
def checkout(request):
    params_dict = {
        'razorpay_order_id': request.POST.get('razorpay_order_id'),
        'razorpay_payment_id': request.POST.get('razorpay_payment_id'),
        'razorpay_signature': request.POST.get('razorpay_signature')
    }
    # client.utility.verify_payment_signature(params_dict)
    try:
        client.utility.verify_payment_signature(params_dict)
        messages.success(request,"Payment successful")
    except:
        messages.success(request,"Payment failed")
    return HttpResponseRedirect(reverse('blogs:blogs-index'))

order/templates/order/create.html
{% extends 'blogs/base.html' %}
{% block content %}
<form class="" action="" method="post">
  <input type="text" name="" value="">
  <button type="submit" name="button">Checkout</button>
  <button id="rzp-button1">Pay</button>
  <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
  <script>
    var options = {    
      "key": "rzp_test_Qrum48VNd3R8T4", // Enter the Key ID generated from the Dashboard    
      "amount": "", // Amount is in currency subunits. Default currency is INR. Hence, 50000 refers to 50000 paise    
      "currency": "INR",
      "name": "Acme Corp",    
      "description": "Test Transaction",    
      "image": "https://example.com/your_logo",
      "order_id": "{{id}}", //This is a sample Order ID. Pass the `id` obtained in the response of Step 1    
      "callback_url": "{% url 'order:checkout' %}",    
      "prefill": {        
        "name": "Gaurav Kumar",        
        "email": "gaurav.kumar@example.com",
        "contact": "9999999999"    
      },    
      "notes": {        
        "address": "Razorpay Corporate Office"    
      },    
      "theme": {        
        "color": "#F37254"    
      }};
      var rzp1 = new Razorpay(options);
      document.getElementById('rzp-button1').onclick = function(e){    
        rzp1.open();   
        e.preventDefault();
      }
    </script>
</form>

{% endblock %}